### ISSUE TITLE
Magic link not working cross browser/device

### ISSUE THREAD

**Issue by sweebee** [ArtMin96/filament-password-less#8]
Since the passphrase is saved in a session, you cant send the magic link from browser 1 and open de login link in browser 2.

Wouldn't it be better to save the passphrase in the cache?

**Comment by ArtMin96** [comment]
It is also a part of passwordless login. To prevent access from other browsers with the same passphrase. Maybe I'll make changes and allow you to choose whether the passphrase is stored in the database or the session.
